- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - openstack-python37-jobs
      - release-notes-jobs-python3
    check:
      jobs:
        - monasca-tempest-python2-influxdb
        - monasca-tempest-python3-influxdb
        - monasca-tempest-python2-cassandra
        - monasca-tempest-java-influxdb
        - monasca-tempest-java-cassandra
        - docker-build-monasca-service
        - legacy-monasca-persister-maven-build
    gate:
      jobs:
        - monasca-tempest-python2-influxdb
        - monasca-tempest-python3-influxdb
        - monasca-tempest-python2-cassandra
        - monasca-tempest-java-influxdb
        - monasca-tempest-java-cassandra
        - legacy-monasca-persister-maven-build
    post:
      jobs:
        - legacy-monasca-persister-localrepo-upload
